// templates/vite-react-shadcn-spa/src/components/custom/DeleteAlertDialog.tsx
import { type ComponentProps, type ReactElement, useCallback, useRef, useState } from "react"

import { Loader2Icon, Trash2Icon } from "lucide-react"

import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog"

export type DeleteAlertDialogLocale = "zh-CN" | "en-US"

export interface DeleteAlertDialogProps {
  trigger: ReactElement
  onConfirm: () => Promise<void> | void
  title?: string
  description?: string
  subjectName?: string
  confirmText?: string
  cancelText?: string
  errorText?: string
  locale?: DeleteAlertDialogLocale
  disabled?: boolean
  open?: boolean
  onOpenChange?: (open: boolean) => void
}

const COPY = {
  "zh-CN": {
    title: "确认删除",
    description: (subjectName?: string) =>
      subjectName ? `确定要删除“${subjectName}”吗？此操作可能无法撤销。` : "确定要删除此项吗？此操作可能无法撤销。",
    cancel: "取消",
    confirm: "删除",
    error: "删除失败，请稍后重试。",
  },
  "en-US": {
    title: "Confirm deletion",
    description: (subjectName?: string) =>
      subjectName
        ? `Delete “${subjectName}”? This action may not be reversible.`
        : "Delete this item? This action may not be reversible.",
    cancel: "Cancel",
    confirm: "Delete",
    error: "Deletion failed. Please try again.",
  },
} satisfies Record<
  DeleteAlertDialogLocale,
  {
    title: string
    description: (subjectName?: string) => string
    cancel: string
    confirm: string
    error: string
  }
>

type AlertDialogChangeDetails = Parameters<NonNullable<ComponentProps<typeof AlertDialog>["onOpenChange"]>>[1]

export function DeleteAlertDialog({
  trigger,
  onConfirm,
  title,
  description,
  subjectName,
  confirmText,
  cancelText,
  errorText,
  locale = "zh-CN",
  disabled = false,
  open,
  onOpenChange,
}: DeleteAlertDialogProps) {
  const [internalOpen, setInternalOpen] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [hasError, setHasError] = useState(false)
  const submittingRef = useRef(false)
  const isControlled = open !== undefined
  const actualOpen = open ?? internalOpen
  const copy = COPY[locale]

  const setOpen = useCallback(
    (nextOpen: boolean) => {
      if (!isControlled) {
        setInternalOpen(nextOpen)
      }
      onOpenChange?.(nextOpen)
    },
    [isControlled, onOpenChange],
  )

  const handleOpenChange = useCallback(
    (nextOpen: boolean, eventDetails: AlertDialogChangeDetails) => {
      if (submittingRef.current && !nextOpen) {
        eventDetails.cancel()
        return
      }
      if (nextOpen) {
        setHasError(false)
      }
      setOpen(nextOpen)
    },
    [setOpen],
  )

  const handleConfirm = useCallback(async () => {
    if (disabled || submittingRef.current) {
      return
    }

    submittingRef.current = true
    setSubmitting(true)
    setHasError(false)

    try {
      await onConfirm()
      setOpen(false)
    } catch {
      setHasError(true)
    } finally {
      submittingRef.current = false
      setSubmitting(false)
    }
  }, [disabled, onConfirm, setOpen])

  return (
    <AlertDialog open={actualOpen} onOpenChange={handleOpenChange}>
      <AlertDialogTrigger render={trigger} disabled={disabled} />
      <AlertDialogContent aria-busy={submitting} className="motion-reduce:animate-none">
        <AlertDialogHeader>
          <AlertDialogTitle className="flex items-center gap-2">
            <Trash2Icon aria-hidden="true" className="size-5 text-destructive" />
            {title ?? copy.title}
          </AlertDialogTitle>
          <AlertDialogDescription>{description ?? copy.description(subjectName)}</AlertDialogDescription>
        </AlertDialogHeader>

        {hasError && (
          <p role="alert" className="text-destructive text-sm">
            {errorText ?? copy.error}
          </p>
        )}

        <AlertDialogFooter>
          <AlertDialogCancel disabled={submitting}>{cancelText ?? copy.cancel}</AlertDialogCancel>
          <AlertDialogAction
            variant="destructive"
            disabled={disabled || submitting}
            onClick={() => void handleConfirm()}
          >
            {submitting && <Loader2Icon aria-hidden="true" className="animate-spin motion-reduce:animate-none" />}
            {confirmText ?? copy.confirm}
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  )
}

export default DeleteAlertDialog

// templates/vite-vue-shadcn-spa/src/components/custom/DeleteAlertDialog.vue
<script setup lang="ts">
import { Trash2 } from '@lucide/vue'
import { ref } from 'vue'

import {
  AlertDialog,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@/components/ui/alert-dialog'
import { Button } from '@/components/ui/button'
import { Spinner } from '@/components/ui/spinner'

const props = withDefaults(
  defineProps<{
    action: () => Promise<void> | void
    title?: string
    description?: string
    subjectName?: string
    confirmText?: string
    cancelText?: string
    errorText?: string
    disabled?: boolean
  }>(),
  {
    title: '确认删除',
    confirmText: '删除',
    cancelText: '取消',
    errorText: '删除失败，请稍后重试。',
    disabled: false,
  },
)

const emit = defineEmits<{
  success: []
}>()
const open = defineModel<boolean>('open', { default: false })
const pending = ref(false)
const failed = ref(false)

const defaultDescription = () =>
  props.subjectName
    ? `确定要删除“${props.subjectName}”吗？此操作可能无法撤销。`
    : '确定要删除此项吗？此操作可能无法撤销。'

function handleOpenChange(next: boolean) {
  if (pending.value && !next) return
  if (next) failed.value = false
  open.value = next
}

async function confirm() {
  if (props.disabled || pending.value) return

  pending.value = true
  failed.value = false
  try {
    await props.action()
    open.value = false
    emit('success')
  } catch {
    failed.value = true
  } finally {
    pending.value = false
  }
}
</script>

<template>
  <AlertDialog :open="open" @update:open="handleOpenChange">
    <AlertDialogTrigger as-child>
      <slot name="trigger" />
    </AlertDialogTrigger>
    <AlertDialogContent :aria-busy="pending" class="motion-reduce:animate-none">
      <AlertDialogHeader>
        <AlertDialogTitle class="flex items-center gap-2">
          <Trash2 aria-hidden="true" class="text-destructive size-5" />
          <slot name="title">{{ title }}</slot>
        </AlertDialogTitle>
        <AlertDialogDescription>
          <slot name="description">{{ description ?? defaultDescription() }}</slot>
        </AlertDialogDescription>
      </AlertDialogHeader>

      <p v-if="failed" role="alert" class="text-destructive text-sm">
        {{ errorText }}
      </p>

      <AlertDialogFooter>
        <AlertDialogCancel :disabled="pending">{{ cancelText }}</AlertDialogCancel>
        <Button
          type="button"
          variant="destructive"
          :disabled="disabled || pending"
          @click="confirm"
        >
          <Spinner v-if="pending" aria-hidden="true" />
          {{ pending ? '删除中…' : confirmText }}
        </Button>
      </AlertDialogFooter>
    </AlertDialogContent>
  </AlertDialog>
</template>
